name: Deploy to Huawei Cloud

on:
  push:
    branches:
      - main  # 当你推送到 main 分支时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run docs:build

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          REMOTE_HOST: ${{secrets.REMOTE_HOST}}
          REMOTE_USER: root
          TARGET: /usr/share/nginx/html/
          SOURCE: docs/.vuepress/dist/
